name: emby_player
description: "Emby 第三方跨平台播放器"
publish_to: 'none'

version: 1.2.1+4

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # Material Design 3 图标
  cupertino_icons: ^1.0.8

  # --- 播放器核心 ---
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7

  # --- 网络请求 ---
  dio: ^5.7.0

  # --- 状态管理 ---
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # --- 本地存储 ---
  shared_preferences: ^2.3.2

  # --- 路由 ---
  go_router: ^14.6.2

  # --- 图片加载 ---
  cached_network_image: ^3.4.1

  # --- 后台音频 / 锁屏控制 ---
  audio_service: ^0.18.19

  # --- 工具类 ---
  uuid: ^4.5.1
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.2
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0


  cached_network_image: ^3.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

