systemProp.http.proxyHost=192.168.1.110
systemProp.http.proxyPort=7893
systemProp.https.proxyHost=192.168.1.110
systemProp.https.proxyPort=7893
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
android.packagingOptions.jniLibs.useLegacyPackaging=true
